name: CI/CD - Docker

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKERHUB }}
          password: ${{ secrets.PASSWORD_DOCKERHUB }}

      - name: Build imagen
        run: docker build -t ${{ secrets.USER_DOCKERHUB }}/mi-app:latest .

      - name: Push imagen
        run: docker push ${{ secrets.USER_DOCKERHUB }}/mi-app:latest
